### PR TITLE
Add feature to pause auto play when user input is detected

### PR DESCRIPTION
**Pull request by joelbrostrom**
Added a variable `pauseOnUserImput` which takes a `Duration`.
If `autoPlay` is set to true and `pauseOnUserInput` is not null, the
`PageView` will be wrapped in a `GestureDetector` listening for
pan gestures.

Also did some minor consistency changes,
i.e. Hard typed a few untyped values and removed the 'new' keywords.
Almost all values were already hard typed and 'new' was used in
only a few places.
Now each line of code follows the same code convention.

My linting options were different from the projects, so I did my best
to follow the repo manually.
Feel free to auto format the code with the previously used setting!

Premise:
When using a sliding carousel you might want the
user to be able to interact with a slide.
For now, the user can swipe back if he/she see something they
like, but the carousel will keep iterating through its children.
This forces the user to constantly swipe back to the page they
were interacting with.
For example, imagen a commercial display rolling adds in a
waiting room. If something interest a person he or she might
want to pause the slide to read all the information.

This feature lets the developer implement a way too pause the
auto play feature for a set amount of time, resetting each time
new input is detected.
This way the user can interact with the application and after they
leave, it will go back to circling the widgets.

### CODE REVIEW

**Comment by joelbrostrom** [comment]
I was thinking about a bool for toggling  the "pauseOnUserInput" but decided against it.
I think too many variables in the constructor can be messy, and autoPlay must already be set to true in order for it to activate.

**Comment by serenader2014** [comment]
It seems that you're committing multiple file in this PR, and I think some of them should not be added in this PR, can you take a look at this? Also, it's better to provide an option to turn on/off this feature, I think default value set to `true` is ok.

**Comment by joelbrostrom** [comment]
Thanks, 
I added the merge artifacts. 
My bad.

Just to clarify, the feature is only selected if you turn on `autoPlay` and pass a Duration to `pauseOnTouchDuration`.
If you don't pass anything the old functionality will remain.
This means it's backwards compatible and unless you set a `pauseOnTouchDuration` the code will behave as before.  

The on/off bool would only be synthetic sugar with no "real effect".
I can add it, or I can add documentation describing the usage.

Some thing along the lines of:

"Delays the next automatic swipe with the specified Duration whenever touch input is detected.
Each time a touch input is registered the delay is reset, not added.
If autoPlay is set to false or this parameter is set to null, input will be recognized."

**Comment by joelbrostrom** [comment]
I could also write documentation for the other arguments as a separate PR.

**Comment by serenader2014** [comment]
Sounds great! It would be nice if you can add a demo in the example project.

**Comment by serenader2014** [comment]
Also, adding the documentation in this PR is fine, no need to open another one. Thanks in advance.

**Comment by joelbrostrom** [comment]
Sure thing!
Might not get it done tonight, but I'll do my best.

**Comment by joelbrostrom** [comment]
Added example and took the opportunity to restructure the code for readability.
I also added labels between the examples so you know what to look for.
Hope you like it!

I'll do the docs tomorrow!

**Comment by joelbrostrom** [comment]
Realised I have to update the readme file to reflect the changes.
I'll have it done until monday.

**Comment by joelbrostrom** [comment]
Done.
Feature Implemented, example added and .readme updated.
 
Ready for merge.

**Comment by serenader2014** [comment]
Good job! Thank you for implementing this feature and adding the inline doc. But I saw you've changed the `this.updateCallback` to `this.onPageChangedCallback`, I think it's better to keep the origin param, for the backward compatibility. Otherwise it will break user from upgrading from the old version to the new version, since this param is published in the dart pub.

My advice is to keep the `updateCallback`, and alias it to `onPageChangedCallback`, and adding a note in the documentation, to let people use the new param. And we can safely remove the old param in the next major release.

**Comment by joelbrostrom** [comment]
Added deprecation to renamed properties, and added the old values to the new properties for backwards compatibility.
Wrote some assertions to prevent double usage of old/new properties as well as some detailed inlined code.

I also read the flutter style guidelines and and modified the code accordingly.

**Comment by joelbrostrom** [comment]
Nice, can you  bump the version number and update dartlang?
I sat the ChangeLog to 1.0.2 (temporarily) but you should probably bump it to 1.1.0 since it contains new features and deprecates old code.

Maybe I should have done it, but I feel its your call as the owner.
Don't forget to add the new version to the readme file and in the change log.

Thanks for a great library!

**Comment by serenader2014** [comment]
Just published to the dart pub. You should be able to see the v1.1.0 version in the pub's repository.

**Pull request merged**
