### PR TITLE
Add controller to play from outside the carousel widget (#76)

### LINKED ISSUE #69: Add support for determining reason of onPageChanged
It would be useful to know why the page changed, because of autoplay or a user drag. onPageChanged should be a function of index and some information to determine the reason of the page change.

### PR DESCRIPTION
**Pull request by HugoHeneault**
This is my first real flutter package contribution so forgive the errors I might have done 😇 

I refactored a few things to get a controller working. The main one is moving all the options to a `CarouselOptions` class. This is a *breaking change* but I think friction update is really small.

Existing PR might need some fixes to match the new `CarouselOptions` parameter. 

There might be more things to do or in another way, tell me and I'll work on it!

Should 
- fix https://github.com/serenader2014/flutter_carousel_slider/issues/76, 
- fix #69

### CODE REVIEW

**Comment by serenader2014** [comment]
Nice job! Will take a look at this PR in the next two days.

**Comment by HugoHeneault** [comment]
@serenader2014 Yes I will do it asap, if you could just freeze the master in the meanwhile, as I changed lots of things I might have to re-resolve the conflicts many times. :)

**Comment by serenader2014** [comment]
@HugoHeneault Of course. Just inform me when you're finishing.

**Comment by HugoHeneault** [comment]
Well that was faster than I expected. First time I had to rebase on an OS project and the number of commits made me thought it would be harder. 

If I can help you with anything, just tell me :)

Thanks a lot!

**Comment by HugoHeneault** [comment]
It has been squashed to simplify my rebase process but I also integrated a fix based on https://github.com/serenader2014/flutter_carousel_slider/pull/77 with the reason the slider changed, so it should fix #69

**Pull request merged**
