### PR TITLE
Add Null safety support and update example code

### PR DESCRIPTION
**Pull request by prateekmedia**
The current Null safe dev version only causes issues and doesn't work pretty well with null safe and non null safe code.

What this PR does is it add's null safety using the official dart migrate command and adds few additional tweaks in example app and made it use dark mode by default with a switch at the top to turn dark mode on and off.

I have also tried to use Expanded in example where possible to fix overflow problem's based on the resolution.

Also I have acknowledged that null safety is backward compatible which means you can you null safe packages with non-null safe code if you have flutter version 2 or higher.

It is ready to be pulled and pushed to pub.dev.

### CODE REVIEW

**Comment by Tarlochan5268** [comment]
> The current Null safe dev version only causes issues and doesn't work pretty well with null safe and non null safe code.
> 
> What this PR does is it add's null safety using the official dart migrate command and adds few additional tweaks in example app and made it use dark mode by default with a switch at the top to turn dark mode on and off.
> 
> I have also tried to use Expanded in example where possible to fix overflow problem's based on the resolution.
> 
> Also I have acknowledged that null safety is backward compatible which means you can you null safe packages with non-null safe code if you have flutter version 2 or higher.
> 
> It is ready to be pulled and pushed to pub.dev.

wow thanks alot prateekmedia this helped me alot and fixed my issue now my webpage is working

**Comment by charliegaldamez** [comment]
Is this PR will be integrated?

**Comment by prateekmedia** [comment]
> Is this PR will be integrated?

cc @serenader2014 
I hope so, it solves all null safe errors and also enhances the example app.

**Comment by hasanm08** [comment]
Merge this please

**Comment by tivervac** [comment]
@serenader2014 It's been a while since your last commit. Any chance this will get merged? Anything we can do to help?

**Comment by serenader2014** [comment]
PR is merged. I'm very sorry, I'm pretty busy these days.

**Pull request merged**
