### PR TITLE
Fix #21: `enlargeCenterPage` not working with vertial scroll carousel

### LINKED ISSUE #21: Any plan to support vertical scroll carousel?

### PR DESCRIPTION
**Pull request by showgp**

### CODE REVIEW

**Comment by serenader2014** [comment]
This PR can fix the `enlargeCenterPage` issue, but I think maybe we need to reconsider changing the box sizing setting, currently we have `height` and `aspectRatio` params, but this two params are meant for horizontal carousel, for vertical carousel maybe we need a `width` param?

**Comment by joelbrostrom** [comment]
Or, _mainAxisSize_ variable?

**Comment by showgp** [comment]
Maybe `mainAxisSize` is a better choice, but we need replace both `width` and `height` with `mainAxisSize`.

I'll go on to implement `mainAxisSize` later this week to support both horizontal and vertical carousel if we all agree on `mainAxisSize`.

**Comment by serenader2014** [comment]
`mainAxisSize` sounds great. Thank you for taking time to contribute.

**Comment by serenader2014** [comment]
Great! And can you update the documentation for this change?

**Comment by showgp** [comment]
Sure, I'll do it.

**Comment by serenader2014** [comment]
This PR still not be merged to the master branch, so now the `enlargeCenterPage` may still not working for the v1.2.0 version. I'm closing this PR since this PR is not active anymore, and will fix this in v1.2.1.

**Pull request closed without merging**
