### PR TITLE
Fix CarousePageChangedReason.manual never being emitted

### PR DESCRIPTION
**Pull request by HugoHeneault**
This is a redo of #136 without conflicts. Thanks to his robust work I re-implemented! It fixes CarousePageChangedReason.manual never being emitted

### CODE REVIEW

**Comment by HugoHeneault** [comment]
There are some formatting diff, what style are you using? I also deleted tests that created errors on my dart analysis tab (Android Studio)

**Comment by serenader2014** [comment]
Hi @HugoHeneault , it would be nice if you don't change the code formatting, because it makes me hard to review, and it will create conflicts when I need to merge multiple PRs.

**Comment by HugoHeneault** [comment]
@serenader2014 Sure. Just did it. Where does your formatting comes from? Mine (Android Studio) seems to be more "flutter-compliant"

**Comment by atrope** [comment]
As I Stated in my Original PR, This bug still happens even though you closed #136..
I Am using my fork until this is merged..

Thanks @HugoHeneault

**Pull request merged**
